/**
 * Manual Test Script: WhatsApp Document Sending
 *
 * Tests the complete document sending flow:
 * 1. Generate DOCX from content
 * 2. Upload to WaSenderAPI
 * 3. Send via WhatsApp
 *
 * Usage:
 *   TEST_WHATSAPP_NUMBER=+357XXXXXXXX pnpm exec tsx tests/manual/test-whatsapp-document.ts
 *
 * Required env vars:
 *   - WASENDER_API_KEY: Your WaSenderAPI session key
 *   - TEST_WHATSAPP_NUMBER: Phone number to send test to (E.164 format)
 */

import { config } from "dotenv";
config({ path: ".env.local" });

async function runTests() {
  // Dynamic imports after dotenv loads
  const { getWhatsAppClient } = await import("../../lib/whatsapp/client.js");
  const { generateDocx } = await import("../../lib/whatsapp/docx-generator.js");

  console.log("\n=== WhatsApp Document Sending Test ===\n");

  const testPhone = process.env.TEST_WHATSAPP_NUMBER;
  if (!testPhone) {
    console.error(
      "ERROR: TEST_WHATSAPP_NUMBER env var is required\n" +
        "Usage: TEST_WHATSAPP_NUMBER=+357XXXXXXXX pnpm exec tsx tests/manual/test-whatsapp-document.ts"
    );
    process.exit(1);
  }

  const client = getWhatsAppClient();

  if (!client.isConfigured()) {
    console.error(
      "ERROR: WhatsApp client not configured\n" +
        "Make sure WASENDER_API_KEY is set in .env.local"
    );
    process.exit(1);
  }

  console.log("Test phone:", testPhone);
  console.log("Client configured:", client.isConfigured());

  // Test 1: Simple text message
  console.log("\n--- Test 1: Sending text message ---");
  try {
    const textResult = await client.sendMessage({
      to: testPhone,
      text: "Test message from SOFIA WhatsApp integration test",
    });
    console.log("Text message result:", textResult);
  } catch (error) {
    console.error("Text message error:", error);
  }

  // Test 2: Generate and send document
  console.log("\n--- Test 2: Generating and sending document ---");
  try {
    const testContent = `**SOFIA Test Document**

**Generated:** ${new Date().toISOString()}

This is a test document generated by the SOFIA WhatsApp integration.

**Test Section 1: Basic Formatting**
- Item one
- Item two
- Item three

**Test Section 2: Form Fields**
Client Name: _______________
Property Address: _______________
Date: _______________

**Test Section 3: Calculations**
Property Value: €250,000
Transfer Fee (3%): €7,500
VAT (19%): €47,500
Total: €305,000

This document was generated to verify the WhatsApp document sending functionality.`;

    console.log("Generating DOCX...");
    const docBuffer = await generateDocx(testContent);
    console.log(`DOCX generated: ${docBuffer.length} bytes`);

    console.log("Sending document via WhatsApp...");
    const docResult = await client.sendDocument({
      to: testPhone,
      document: docBuffer,
      filename: `SOFIA_Test_${Date.now()}.docx`,
      caption: "Test document from SOFIA integration test",
    });

    console.log("Document send result:", docResult);
  } catch (error) {
    console.error("Document send error:", error);
  }

  // Test 3: Test upload separately
  console.log("\n--- Test 3: Testing upload separately ---");
  try {
    const smallBuffer = Buffer.from("Test content for upload", "utf-8");
    const uploadResult = await client.uploadFile({
      buffer: smallBuffer,
      mimeType: "text/plain",
      filename: "test.txt",
    });
    console.log("Upload result:", uploadResult);
  } catch (error) {
    console.error("Upload error:", error);
  }

  console.log("\n=== Tests Complete ===\n");
}

runTests().catch(console.error);
