/**
 * Upload David Smith's Tala Property to Zyprus
 */

import { config } from "dotenv";

config({ path: ".env.local" });

const baseUrl = process.env.ZYPRUS_API_URL || "https://dev9.zyprus.com";
const clientId = process.env.ZYPRUS_CLIENT_ID;
const clientSecret = process.env.ZYPRUS_CLIENT_SECRET;

async function getToken(): Promise<string> {
  const response = await fetch(`${baseUrl}/oauth/token`, {
    method: "POST",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      "User-Agent": "SophiaAI",
    },
    body: new URLSearchParams({
      grant_type: "client_credentials",
      client_id: clientId!,
      client_secret: clientSecret!,
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`OAuth failed: ${response.status} - ${errorText}`);
  }

  const tokenData = await response.json();
  return tokenData.access_token;
}

async function uploadImage(
  token: string,
  imageUrl: string,
  index: number
): Promise<string> {
  console.log(`Uploading image ${index + 1}: ${imageUrl}`);

  const imageResponse = await fetch(imageUrl);
  if (!imageResponse.ok) {
    throw new Error(`Failed to fetch image: ${imageResponse.status}`);
  }

  const imageBlob = await imageResponse.blob();
  const contentType = imageResponse.headers.get("content-type") || "image/jpeg";
  const ext = contentType.split("/")[1] || "jpg";
  const filename = `property-image-${index + 1}.${ext}`;

  const uploadResponse = await fetch(
    `${baseUrl}/jsonapi/node/property/field_gallery_`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "User-Agent": "SophiaAI",
        "Content-Type": "application/octet-stream",
        "Content-Disposition": `file; filename="${filename}"`,
      },
      body: imageBlob,
    }
  );

  if (!uploadResponse.ok) {
    const errorText = await uploadResponse.text();
    throw new Error(
      `Image upload failed: ${uploadResponse.status} - ${errorText}`
    );
  }

  const data = await uploadResponse.json();
  console.log(`Successfully uploaded image ${index + 1}: ${data.data.id}`);
  return data.data.id;
}

async function main() {
  console.log("=== UPLOADING DAVID SMITH'S TALA PROPERTY ===\n");

  const token = await getToken();
  console.log("Got OAuth token\n");

  // Taxonomy IDs
  const TALA_LOCATION_ID = "5efac119-c841-42f6-9c0a-bc6dcb485c1e";
  const DETACHED_HOUSE_ID = "76b4fa8e-de7e-4232-85ac-869dca3620f4";
  const SALE_LISTING_TYPE_ID = "8f187816-a888-4cda-a937-1cee84b9c0ee";

  // Indoor features
  const AIR_CONDITIONING_ID = "f577829f-8cbe-4ba8-9ce8-e67a30b6fe76";
  const CENTRAL_HEATING_ID = "4f2523f7-9fde-4390-b532-c0da52644632";
  const GUEST_TOILET_ID = "5e2a90da-6836-444b-8d72-a5f810d3a9e5";
  const COVERED_PARKING_ID = "432ac572-ed64-4107-a818-19a8a22c5371";

  // Outdoor features
  const PHOTOVOLTAIC_ID = "cf0e9658-bd22-4d8d-988e-b579f7139c1a";
  const UNCOVERED_PARKING_ID = "695d4e05-83df-4345-8f03-911302e96784";

  // Upload image first
  const imageUrl =
    "https://i.ibb.co/4ndWtjWN/2-bedroom-detached-house-sale-kamares-tala-paphos-41330-784983.jpg";
  let imageId: string | null = null;

  try {
    imageId = await uploadImage(token, imageUrl, 0);
  } catch (err) {
    console.error("Image upload failed:", err);
    console.log("Continuing without image...\n");
  }

  // Build property payload
  const payload = {
    data: {
      type: "node--property",
      attributes: {
        status: false,
        title: "3 Bedroom Detached House in Tala, Paphos",
        body: {
          value: `Beautiful 3 bedroom detached house located in the popular village of Tala, Paphos.

Property Features:
• 3 Bedrooms
• 2 Bathrooms + 1 Guest W/C
• Net Indoor Area: 140m²
• Covered Veranda: 30m²
• Plot Area: 400m²
• Covered and uncovered parking
• Air Conditioning
• Photovoltaic System
• Central Heating
• No Swimming Pool

Notes: Title deeds are clean, copy available soon. Owner is currently living in the property and will vacate once sold.

Contact: David Smith - 99123456`,
          format: "plain_text",
        },
        field_ai_state: "draft",
        field_ai_generated: true,
        field_ai_message: {
          value: "Generated by SOFIA AI via Claude Code CLI",
        },
        field_ai_probably_exists: false,
        field_price: "480000",
        field_covered_area: 140,
        field_land_size: 400,
        field_no_bedrooms: 3,
        field_no_bathrooms: 3, // 2 bathrooms + 1 guest WC = 3 total
        field_no_kitchens: 1,
        field_no_living_rooms: 1,
        field_own_reference_id: "3456-SMITH-TALA",
        field_year_built: 2020,
        field_new_build: false,
        field_property_notes:
          "Title deeds are clean, will have a copy soon. Owner is living inside and will vacate once sold. Owner: David Smith - 99123456",
        field_map: {
          value: "POINT (32.432358 34.830077)",
          geo_type: "Point",
          lat: 34.830_077,
          lon: 32.432_358,
          latlon: "34.830077,32.432358",
        },
      },
      relationships: {
        field_location: {
          data: { type: "node--location", id: TALA_LOCATION_ID },
        },
        field_property_type: {
          data: { type: "taxonomy_term--property_type", id: DETACHED_HOUSE_ID },
        },
        field_listing_type: {
          data: {
            type: "taxonomy_term--listing_type",
            id: SALE_LISTING_TYPE_ID,
          },
        },
        field_indoor_property_features: {
          data: [
            {
              type: "taxonomy_term--indoor_property_views",
              id: AIR_CONDITIONING_ID,
            },
            {
              type: "taxonomy_term--indoor_property_views",
              id: CENTRAL_HEATING_ID,
            },
            {
              type: "taxonomy_term--indoor_property_views",
              id: GUEST_TOILET_ID,
            },
            {
              type: "taxonomy_term--indoor_property_views",
              id: COVERED_PARKING_ID,
            },
          ],
        },
        field_outdoor_property_features: {
          data: [
            {
              type: "taxonomy_term--outdoor_property_features",
              id: PHOTOVOLTAIC_ID,
            },
            {
              type: "taxonomy_term--outdoor_property_features",
              id: UNCOVERED_PARKING_ID,
            },
          ],
        },
        ...(imageId && {
          field_gallery_: {
            data: [{ type: "file--file", id: imageId }],
          },
        }),
      },
    },
  };

  console.log("Creating property listing...\n");

  const response = await fetch(`${baseUrl}/jsonapi/node/property`, {
    method: "POST",
    headers: {
      "Content-Type": "application/vnd.api+json",
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.api+json",
      "User-Agent": "SophiaAI",
    },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    console.error("API Error:", response.status);
    console.error("Error details:", JSON.stringify(errorData, null, 2));
    throw new Error(`API error: ${response.status}`);
  }

  const result = await response.json();
  const propertyId = result.data.id;
  const nodeId = result.data.attributes.drupal_internal__nid;
  const propertyUrl = `${baseUrl}/node/${nodeId}`;

  console.log("\n=== SUCCESS ===");
  console.log(`Property UUID: ${propertyId}`);
  console.log(`Property Node ID: ${nodeId}`);
  console.log(`Property URL: ${propertyUrl}`);
  console.log(
    "\nThe listing is now on dev9.zyprus.com as an UNPUBLISHED DRAFT."
  );
  console.log("An admin will need to review and publish it.");
}

main().catch(console.error);
